#!/bin/bash


print_status() {
    echo
    echo "## $1"
    echo
}

if test -t 1; then # if terminal
    ncolors=$(which tput > /dev/null && tput colors) # supports color
    if test -n "$ncolors" && test $ncolors -ge 8; then
        termcols=$(tput cols)
        bold="$(tput bold)"
        underline="$(tput smul)"
        standout="$(tput smso)"
        normal="$(tput sgr0)"
        black="$(tput setaf 0)"
        red="$(tput setaf 1)"
        green="$(tput setaf 2)"
        yellow="$(tput setaf 3)"
        blue="$(tput setaf 4)"
        magenta="$(tput setaf 5)"
        cyan="$(tput setaf 6)"
        white="$(tput setaf 7)"
    fi
fi

print_bold() {
    title="$1"
    text="$2"

    echo
    echo "${red}================================================================================${normal}"
    echo "${red}================================================================================${normal}"
    echo
    echo -e "  ${bold}${yellow}${title}${normal}"
    echo
    echo -en "  ${text}"
    echo
    echo "${red}================================================================================${normal}"
    echo "${red}================================================================================${normal}"
}


bail() {
    echo 'Error executing command, exiting'
    exit 1
}

exec_cmd_nobail() {
    echo "+ $1"
    bash -c "$1"
}

exec_cmd() {
    exec_cmd_nobail "$1" || bail
}




print_bold "Instalar Bitcoin" "${bold}Comando Update"
apt-add-repository ppa:bitcoin/bitcoin
sudo apt-get update
apt-get install bitcoind -y
sudo add-apt-repository --remove ppa:bitcoin/bitcoin
sudo apt-get update
bitcoind -daemon
sleep 7
ps aux | grep -ie bitcoind | awk '{print $2}' | xargs kill -9




print_bold "Creando Conf de Moneda" "${bold}Instalando..."
echo "" >  /root/.bitcoin/bitcoin.conf
echo "" >>  /root/.bitcoin/bitcoin.conf
echo "testnet=1" >>  /root/.bitcoin/bitcoin.conf
echo "daemon=1" >>  /root/.bitcoin/bitcoin.conf
echo "keypool=10000" >>  /root/.bitcoin/bitcoin.conf
echo "prune=10000" >>  /root/.bitcoin/bitcoin.conf
echo "bind=0.0.0.0" >>  /root/.bitcoin/bitcoin.conf
echo "rest=1" >>  /root/.bitcoin/bitcoin.conf
echo "rpcbind=*" >>  /root/.bitcoin/bitcoin.conf
echo "rpcallowip=0.0.0.0/0" >>  /root/.bitcoin/bitcoin.conf
echo "rpcallowip=::/0" >>  /root/.bitcoin/bitcoin.conf
echo "rpcuser=marialadelbarrio" >>  /root/.bitcoin/bitcoin.conf
echo "rpcpassword=supermanputito" >>  /root/.bitcoin/bitcoin.conf
echo "rpcport=7410" >>  /root/.bitcoin/bitcoin.conf
echo "fallbackfee=0.00003" >>  /root/.bitcoin/bitcoin.conf
echo "mintxfee=0.00001" >>  /root/.bitcoin/bitcoin.conf
echo "" >>  /root/.bitcoin/bitcoin.conf
echo "" >>  /root/.bitcoin/bitcoin.conf


