#!/bin/bash


print_status() {
    echo
    echo "## $1"
    echo
}

if test -t 1; then # if terminal
    ncolors=$(which tput > /dev/null && tput colors) # supports color
    if test -n "$ncolors" && test $ncolors -ge 8; then
        termcols=$(tput cols)
        bold="$(tput bold)"
        underline="$(tput smul)"
        standout="$(tput smso)"
        normal="$(tput sgr0)"
        black="$(tput setaf 0)"
        red="$(tput setaf 1)"
        green="$(tput setaf 2)"
        yellow="$(tput setaf 3)"
        blue="$(tput setaf 4)"
        magenta="$(tput setaf 5)"
        cyan="$(tput setaf 6)"
        white="$(tput setaf 7)"
    fi
fi

print_bold() {
    title="$1"
    text="$2"

    echo
    echo "${red}================================================================================${normal}"
    echo "${red}================================================================================${normal}"
    echo
    echo -e "  ${bold}${yellow}${title}${normal}"
    echo
    echo -en "  ${text}"
    echo
    echo "${red}================================================================================${normal}"
    echo "${red}================================================================================${normal}"
}


bail() {
    echo 'Error executing command, exiting'
    exit 1
}

exec_cmd_nobail() {
    echo "+ $1"
    bash -c "$1"
}

exec_cmd() {
    exec_cmd_nobail "$1" || bail
}




print_bold "Instalar DASH" "${bold}Comando Update"
cd /tmp
mkdir dash
chmod 777 dash
cd dash
wget "https://github.com/dashpay/dash/releases/download/v0.12.3.3/dashcore-0.12.3.3-x86_64-linux-gnu.tar.gz"
tar -xzvf dashcore-0.12.3.3-x86_64-linux-gnu.tar.gz
cd /tmp/dash/dashcore-0.12.3/bin
mv dashd /usr/bin/dashd
mv dash-cli /usr/bin/dash-cli
dashd -daemon
sleep 7
ps aux | grep -ie dashd | awk '{print $2}' | xargs kill -9




print_bold "Creando Conf de Moneda" "${bold}Instalando..."
echo "" >  /root/.dash/dash.conf
echo "" >>  /root/.dash/dash.conf
echo "testnet=1" >>  /root/.dash/dash.conf
echo "daemon=1" >>  /root/.dash/dash.conf
echo "keypool=10000" >>  /root/.dash/dash.conf
echo "prune=10000" >>  /root/.dash/dash.conf
echo "bind=0.0.0.0" >>  /root/.dash/dash.conf
echo "rest=1" >>  /root/.dash/dash.conf
echo "rpcbind=*" >>  /root/.dash/dash.conf
echo "rpcallowip=0.0.0.0/0" >>  /root/.dash/dash.conf
echo "rpcallowip=::/0" >>  /root/.dash/dash.conf
echo "rpcuser=marialadelbarrio" >>  /root/.dash/dash.conf
echo "rpcpassword=supermanputito" >>  /root/.dash/dash.conf
echo "rpcport=8520" >>  /root/.dash/dash.conf
echo "fallbackfee=0.00003" >>  /root/.dash/dash.conf
echo "mintxfee=0.00001" >>  /root/.dash/dash.conf
echo "" >>  /root/.dash/dash.conf
echo "" >>  /root/.dash/dash.conf


