#!/bin/bash

 
echo "Install PHP"
sudo apt-get install -y php-fpm php-mysql
echo "cgi.fix_pathinfo=0" >>  /etc/php/7.2/fpm/php.ini
sudo systemctl restart php7.2-fpm

echo "Install dependences PHP"
sudo apt-get install -y php7.2-common php7.2-cli php7.2-cgi php-sqlite3 php-pear php-mysql php-gmp php-gd php-dev php-curl php-common php-cli php-cgi php-all-dev libnet-libidn-perl
sudo apt-get install -y php7.2-recode php7.2-snmp php7.2-xml php7.2-tidy php7.2-sqlite3 php7.2-readline php7.2-pspell php7.2-pgsql php7.2-opcache php7.2-odbc php7.2-mysql php7.2-ldap php7.2-json php7.2-gmp php7.2-gd php7.2-curl
sudo apt-get install -y libphp-phpmailer php7.2-zip php7.2-sybase php7.2-soap php7.2-phpdbg php7.2-mbstring php7.2-intl php7.2-interbase php7.2-imap php7.2-fpm php7.2-enchant php7.2-dba php7.2-bz2 php7.2-bcmath php7.1-mapi
sudo systemctl restart php7.2-fpm
sudo systemctl restart php7.2-fpm

echo "Check PHP"
sudo systemctl status php7.2-fpm


echo "Install PHP pthreads"

echo "Steep 1 of 11";
sudo apt update -y
sudo apt install -y libzip-dev bison autoconf build-essential pkg-config git-core libltdl-dev libbz2-dev libxml2-dev libxslt1-dev libssl-dev libicu-dev libpspell-dev libenchant-dev libmcrypt-dev libpng-dev libjpeg8-dev libfreetype6-dev libmysqlclient-dev libreadline-dev libcurl4-openssl-dev

echo "Steep 2 of 11";
cd $HOME
wget https://github.com/php/php-src/archive/php-7.2.2.tar.gz
tar --extract --gzip --file php-7.2.2.tar.gz

echo "Steep 3 of 11";
cd $HOME/php-src-php-7.2.2
./buildconf --force

echo "Steep 4 of 11";
CONFIGURE_STRING="--prefix=/etc/php7 --with-bz2 --with-zlib --enable-zip --disable-cgi \
   --enable-soap --enable-intl --with-openssl --with-readline --with-curl \
   --enable-ftp --enable-mysqlnd --with-mysqli=mysqlnd --with-pdo-mysql=mysqlnd \
   --enable-sockets --enable-pcntl --with-pspell --with-enchant --with-gettext \
   --with-gd --enable-exif --with-jpeg-dir --with-png-dir --with-freetype-dir --with-xsl \
   --enable-bcmath --enable-mbstring --enable-calendar --enable-simplexml --enable-json \
   --enable-hash --enable-session --enable-xml --enable-wddx --enable-opcache \
   --with-pcre-regex --with-config-file-path=/etc/php7/cli \
   --with-config-file-scan-dir=/etc/php7/etc --enable-cli --enable-maintainer-zts \
   --with-tsrm-pthreads --enable-debug --enable-fpm \
   --with-fpm-user=www-data --with-fpm-group=www-data"

./configure $CONFIGURE_STRING

echo "Steep 5 of 11";
make && sudo make install

echo "Steep 6 of 11";
sudo chmod o+x /etc/php7/bin/phpize
sudo chmod o+x /etc/php7/bin/php-config

echo "Steep 7 of 11";
git clone https://github.com/krakjoe/pthreads.git

echo "Steep 8 of 11";
cd pthreads
/etc/php7/bin/phpize

echo "Steep 9 of 11";
./configure \
--prefix='/etc/php7' \
--with-libdir='/lib/x86_64-linux-gnu' \
--enable-pthreads=shared \
--with-php-config='/etc/php7/bin/php-config'

echo "Steep 10 of 11";
make && sudo make install

echo "Steep 11 of 11";
cd $HOME/php-src-php-7.2.2
sudo mkdir -p /etc/php7/cli/
sudo cp php.ini-production /etc/php7/cli/php.ini
echo "extension=pthreads.so" | sudo tee -a /etc/php7/cli/php.ini
echo "zend_extension=opcache.so" | sudo tee -a /etc/php7/cli/php.ini

echo "Test pthreads";
/etc/php7/bin/php -i  | grep -i thread



echo "Creando Tablas locales de Mysql";
mysql -u root -p < /home/lomeli/tmp/local.sql



#curl -sL https://raw.githubusercontent.com/miguelomeli/setups/master/xxxxx | sudo -E bash -


